sudo: false
language: node_js
node_js:
- stable
install: npm update
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: LkTOjyFOVoRUOxfJ88WVeV7jDJtClP+/UNcjIZnfyIZ/tskH1yT8iwZorHFvAisvJ0wbEBVuHw4GnYwqoXeDbeKHYGHC/2KSHEvYnsxuBgAo2bIixRcLtnT5+BJQWlKSsQFeyoXjVi2fJOMf2Ly+4CZIG/LJ5PPYIdM5kaOY8+yLq7ssaaFYRCPek1Dh2fQWeNAim2dsHc3W4Ppy15lHbhXWRyWYBLiF6YshOFnVBvsxzMnkIcsKdj+jJXAYeB3tCevMSub4C8v+tKgHZ/31qycuvmoPIMofmy244NnqdG/n6mYWqBSNQSDjNckOxiA4IDfTz7P+XjZj2X3eTcxZeMp7pejMGwolISDHmhxqopDoPPpWrP4+/oHBsXetUl37phwZhe9hnj1jKCNh1xzeLyf+wHPM1yQ6adXrIJ1mT8MYcVi1cCmbyXR2fxKHuLU9TWY/qmINFW2+BCZm5WPkwOI3mvotNeZDXx7+V19fIh5YklhuU3XshIqHfZ8WtwgRQJsOfq1FRD+yu7WbzCCPTHz5zJsTQDEI69UY7XFRzLVweoAywagB4B83r6JoaObYT7/ZIZUqHSaI9gOd4HbKxcoMh4/1EOm1xdDVRf+nhKdyb7zR/FTRe/qJvLHHJPv4wDwyie7/k7jO1kjEXdiao9iTlDiJ+JCeHd+IoOpl0UM=
  on:
    tags: true
    repo: dominicbarnes/node-graph-toposort
